import { AppProps } from "next/app";
import { ThirdwebProvider } from "@thirdweb-dev/react";
import { ChainId } from "@thirdweb-dev/sdk";
import Head from "next/head";

import "src/styles/globals.css";
import { Header } from "src/components";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Spiritverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
      </Head>

      <ThirdwebProvider
        desiredChainId={ChainId.Mumbai}
        chainRpc={{
          [ChainId.Mumbai]:
            "https://polygon-mumbai.infura.io/v3/49746fb65f314711bd77a5fe54d48416",
        }}
        sdkOptions={{
          gasSettings: { speed: "fast" },
          readonlySettings: {
            chainId: ChainId.Mumbai,
            rpcUrl:
              "https://polygon-mumbai.infura.io/v3/49746fb65f314711bd77a5fe54d48416",
          },
          gasless: {
            openzeppelin: {
              relayerUrl:
                "https://api.defender.openzeppelin.com/autotasks/2fba718d-6117-4836-9753-ac06f89d4754/runs/webhook/85d2e851-fef8-490d-8b42-d1edfa860c60/Q4RmRWJ6773PcqJsg42uDb",
            },
          },
        }}
      >
        <Header />
        <main className="p-2">
          <Component {...pageProps} />
        </main>
      </ThirdwebProvider>
    </>
  );
}

export default MyApp;
